### ISSUE TITLE
http_body_parser tries to parse body of GET Requests

### ISSUE THREAD

**Issue by davidmehren** [redstone-dart/redstone.dart#131]
I just found out that http_body_parser tries to parse the body of every request if the header 'Content-Type' is set to 'application/json'. If the request is GET this obviously fails because GET requests dont have a body.

Stack trace of the error:
Failed to execute .getDays - FormatException: Unexpected end of input (at character 1)

^

dart:convert                                       JsonCodec.decode
package:redstone/src/http_body_parser.dart 101:60  _parseRequestBody.<fn>

**Comment by Pacane** [comment]
Does anyone know what the standard is for this? I know from that a GET request [can actually have a body](http://stackoverflow.com/questions/978061/http-get-with-request-body).

> A message-body MUST NOT be included in a request if the specification of the request method (section 5.1.1) does not allow sending an entity-body in requests. A server SHOULD read and forward a message-body on any request; if the request method does not include defined semantics for an entity-body, then the message-body SHOULD be ignored when handling the request.

Although, nowhere in the [GET specification](http://www.w3.org/Protocols/rfc2616/rfc2616-sec9.html#sec9.3) do I see anything saying that it's forbidden to send an entity-body in such request. [As opposed to [OPTIONS request](http://www.w3.org/Protocols/rfc2616/rfc2616-sec9.html#sec9.2) where it's explicitly written.]

I wonder what others think about this. I feel something's wrong with ignoring the request, but I also feel like it's not so good to throw an error (for instance, [Google throws a BAD REQUEST error when this happens.](http://stackoverflow.com/a/17384851/505810)

Any thoughts? @kaendfinger @cgarciae

**Comment by TheBosZ** [comment]
:+1: Just ran into this problem myself.

I have an Angular2 (Ionic2) app talking to my server and when I try to
`http.get('server/users')` my auth interceptor throws up.

According to the [Angular2 docs](https://angular.io/docs/ts/latest/api/http/Http-class.html) get doesn't even have an option for a body.

**Comment by Pacane** [comment]
Can you show the code you use to initiate the query? It is likely to be invalid to provide a body for a `GET`.

**Comment by TheBosZ** [comment]
```
var headers = AuthInterceptor.generateHeaders(url, null, 'GET', contentType, 'bob', 'lskfjwefweljfk');
var result = this.http.get(url, {
    headers: headers
});
```

Notice that there's only 2 parameters for get: url and options.

**Comment by Pacane** [comment]
so this is JS right?

**Comment by TheBosZ** [comment]
That particular bit of code is Typescript, but a Javascript version would look exactly the same.

To me, it seems like a simple fix would be to change http_body_impl to check the body before trying to decode it. Any reason why that wouldn't work?

**Comment by Pacane** [comment]
No that would be fine I suppose. I just didn't know if we should throw an error or just ignore the body on a GET. There doesn't seem to be a standard for this AFAIK. If you know anything about such standard, let me know.

**Comment by Pacane** [comment]
Anyway, if you want to contribute it, I'd be glad to merge it, otherwise I'll add this to my todo list. :)

**Comment by TheBosZ** [comment]
Well, [this response](http://stackoverflow.com/a/983458/1734975) on that Stack Overflow post has this bit:

> So, yes, you can send a body with GET, and no, it is never useful to do so.

And reading the comments and other thoughts, it sounds like the best idea is parse it if it's there, but otherwise ignore it.

Webstorm is being stupid about letting me edit imported libraries, but I'll try my idea and see if I like the results.

**Comment by Pacane** [comment]
So "parse it if it's there", and do what with it?

**Comment by TheBosZ** [comment]
Now that I've had a chance to look at what the code actually does, I don't really see an easy way to do what I was thinking. I was thinking he had more control in how it parses, but now I see that it's handled outside of this library.

Playing around with it, what if we did something like this in request_parser.dart, around line 37, essentially ignoring a body if it's not expected:

`if (_body == null && validBodyMethods.contains(httpRequest.method)) {`

**Comment by Pacane** [comment]
I think this could be something doable yes. I still wonder if we should parse it or not. I think we should just  ignore the body when it's a GET.

**Comment by TheBosZ** [comment]
I agree. From the SO post, that seems to be an acceptable solution.

**Comment by Pacane** [comment]
@TheBosZ Fix deployed in the wild with v0.6.5. Thanks again!

**Comment by fwgreen** [comment]
This issue persists if you use [Postman](https://www.getpostman.com/) and don't explicitly disable `application/json` on the request body.
